### ISSUE TITLE
GCYS java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by smolljam** [GregTechCEu/gregicality-science#76] opened 2022-09-10 10:25 UTC
### GregTech CEu Version

2.4.0 GCYS compat

### Gregicality Multiblocks Version

1.1.4 GCYS

### Gregicality Science Version

0.0.1 a

### Environment

Singplayer

### Side Crashed

Client

### New Worlds

No

### Steps to Reproduce

start the client with mod that listed in report and it crash 

### Crash Report

https://gist.github.com/smolljam/827642b3acff507b1d6344c32fd0649c

**Comment by AiDSl** [comment] 2022-10-02 12:56
same problem with different mod combination:
[crash-2022-10-02_20.51.51-client.txt](https://github.com/GregTechCEu/gregicality-science/files/9692550/crash-2022-10-02_20.51.51-client.txt)

**Comment by htmlcsjs** [comment] 2022-10-29 15:08
Not actually an issue with GCY:S, but CEu.

Duplicate of [GregTech#1169](https://github.com/GregTechCEu/GregTech/issues/1169)

**Closed as completed by htmlcsjs** 2022-10-29 15:08 UTC
